# This file was generated by GoReleaser. DO NOT EDIT.
cask "frame" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "aed44b0e00c5c37dd74de022a7c4b6a26a53acbb99286c8266f00ba55ac0db36"
      url "https://github.com/dirisha-dev/homebrew-frame/releases/download/v#{version}/frame_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7d9c57da3ce958f6cddafbcebafa3c935d352e9f07b5a96e82045344a52188cf"
      url "https://github.com/dirisha-dev/homebrew-frame/releases/download/v#{version}/frame_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6345d5300f5d1bedc9bec974aff3afa7317208662ae0bfee5d507787209d274c"
      url "https://github.com/dirisha-dev/homebrew-frame/releases/download/v#{version}/frame_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1e05589bedb70b20e5664561f782baa3f432e42fd947fc1f0b688abf3a7e9025"
      url "https://github.com/dirisha-dev/homebrew-frame/releases/download/v#{version}/frame_#{version}_linux_arm64.tar.gz"
    end
  end

  name "frame"
  desc "Locally-bound REST API for launching, snapshotting, and archiving AI agent sandboxes"
  homepage "https://github.com/dirisha-dev/frame"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "lima",
    ]

  binary "frame"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/frame"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    frame runs agent sandboxes inside a Linux VM (containerd + gVisor). Create it and
    bring up the API with:
      frame bootstrap
      frame doctor
  EOS
end
