# This file was generated by GoReleaser. DO NOT EDIT.
cask "frame" do
  version "0.6.4"

  on_macos do
    on_intel do
      sha256 "9fa3228961ad6ab198b997fb4d5ca26a1b278dc0cee1dd78cb695a461c3d1b55"
      url "https://github.com/dirisha-dev/homebrew-frame/releases/download/v#{version}/frame_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "698a6ee751bc8e1b2188f0070ba14e2de74e62b359a6c7732aaec596a4b7f9a1"
      url "https://github.com/dirisha-dev/homebrew-frame/releases/download/v#{version}/frame_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2985f8158c5c9d284dd6ab523e7f8c47440bdeaa80d4eec63407a76821d603e8"
      url "https://github.com/dirisha-dev/homebrew-frame/releases/download/v#{version}/frame_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c9422489678fd8e2c30b2f6d0ed4e38104f0f5220219cd0c79fcd971099ed1d0"
      url "https://github.com/dirisha-dev/homebrew-frame/releases/download/v#{version}/frame_#{version}_linux_arm64.tar.gz"
    end
  end

  name "frame"
  desc "Locally-bound REST API for launching, snapshotting, and archiving AI agent sandboxes"
  homepage "https://github.com/dirisha-dev/frame"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "lima",
    ]

  binary "frame"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/frame"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    frame runs agent sandboxes inside a Linux VM (containerd + gVisor). Create it and
    bring up the API with:
      frame bootstrap
      frame doctor
  EOS
end
