# This file was generated by GoReleaser. DO NOT EDIT.
cask "frame" do
  version "0.11.0"

  on_macos do
    on_intel do
      sha256 "bd3711bd18da96e0665d7d0784a16eeb9030a4b5bdb40d4c60a80111960401e1"
      url "https://github.com/dirisha-dev/homebrew-frame/releases/download/v#{version}/frame_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8422819417c02e57432408f1e4e6e1ee9965ab71691702a44cde5376b42e57d3"
      url "https://github.com/dirisha-dev/homebrew-frame/releases/download/v#{version}/frame_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "142306d61ec4e0ac16beb83aceee36ed674a32d6b7377ff68d81b31b12fde527"
      url "https://github.com/dirisha-dev/homebrew-frame/releases/download/v#{version}/frame_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f6ba96b22cbe3405a9b198f09ffd57f1c2bf7ea060353796ca3b4f561ff233ae"
      url "https://github.com/dirisha-dev/homebrew-frame/releases/download/v#{version}/frame_#{version}_linux_arm64.tar.gz"
    end
  end

  name "frame"
  desc "Locally-bound REST API for launching, snapshotting, and archiving AI agent sandboxes"
  homepage "https://github.com/dirisha-dev/frame"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "lima",
    ]

  binary "frame"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/frame"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    frame runs agent sandboxes inside a Linux VM (containerd + gVisor). Create it and
    bring up the API with:
      frame bootstrap
      frame doctor
  EOS
end
